# Don't touch pls
ConfigVersion: "${project.version}"

# Just for information
MinimumQuickShopVersion: "v2.0.0" 

# Debug options, don't touch unless needed
#
# DebugLevel: 0 = no debug, 1 = debug, 2 = debug with stack traces
#
DebugLevel: 0
ForcedLanguage: EN

DatabaseMySQL: false
DatabaseHost: "localhost"
DatabasePort: 3306
DatabaseName: "OxideQSRStats"
DatabaseUser: "root"
DatabasePassword: "passwd"
DatabasePrefix: ""
DatabaseUseSSL: "false"
DatabaseQueue: "true"
# Timeout in seconds
DatabaseTimeOut: 30