name: ${name}
main: ${package}.${mainclass}
version: ${project.version}
api-version: ${apiversion}
author: ${developer}
description: ${description}
depend: [QuickShop]
commands:
  oxqs:
    description: Main command. See /oxqs help for more information
    usage: /oxqs 